stages:
  - build
  - sonar
buildProject:
  image: node:7.10.0
  stage: build
  script:
    -  npm install
    -  npm run build.prod
sonarQubeAnalysis:
  image: netlogistikrobot/sonar-scanner
  stage: sonar
  script:
    -  npm install
    -  echo "sonar.host.url=http://sonar.netlogistik.com" >> /opt/sonar-scanner/conf/sonar-scanner.properties
    -  sonar-scanner
  only:
    - master@dna/web
