let LOGIN_CONSTANTS = {
    LOGIN_PASSWORD: 'LOGIN_PASSWORD',
    LOGIN_USERNAME: 'LOGIN_USERNAME',
    LOGIN_WELCOME_TO_OPM: 'LOGIN_WELCOME_TO_OPM',
    LOGIN_INVALID_USER_OR_PASSWORD: 'LOGIN_INVALID_USER_OR_PASSWORD',
    LOGOUT_OPM: 'LOGOUT_OPM'
};

export { LOGIN_CONSTANTS };
