

let MESSAGE_CONSTANTS = {
  APP_SUCCESS_TITLE: 'APP_SUCCESS_TITLE',
  APP_ERROR_TITLE: 'APP_ERROR_TITLE',
  APP_INFORMATION_TITLE: 'APP_INFORMATION_TITLE',
  APP_REQUIRED_FIELD: 'APP_REQUIRED_FIELD',
  APP_INVALID_PATTERN: 'APP_INVALID_PATTERN',
  APP_HOME_MODULE_TITLE: 'APP_HOME_MODULE_TITLE',
  APP_ACCEPT: 'APP_ACCEPT',
  APP_CANCEL: 'APP_CANCEL',
  APP_SAVE: 'APP_SAVE',
  APP_LOGIN: 'APP_LOGIN'
};


export { MESSAGE_CONSTANTS };
