let CONFIRM_ORDER_CONSTANTS = {
    CONFIRM: "CONFIRM",
    DELIVERY_DATE: "DELIVERY_DATE",
    REQUEST_PERSON: "REQUEST_PERSON",
    REQUESTED_PRODUCTS: "REQUESTED_PRODUCTS"
};

export { CONFIRM_ORDER_CONSTANTS };