let CREATE_ORDER_CONSTANTS = {
    ORDER_BY_CATALOG: 'ORDER_BY_CATALOG',
    ORDER_INFORMATION: 'ORDER_INFORMATION',
    ACCOUNT: 'ACCOUNT',
    ESTIMATED_DELIVERY_DATE: 'ESTIMATED_DELIVERY_DATE',
    REQUEST_PERSON_NAME: 'REQUEST_PERSON_NAME',
    TOTALS: 'TOTALS',
    SAVE: 'SAVE',
    ERROR_TO_GET_PRODUCTS: 'ERROR_TO_GET_PRODUCTS',
    ERROR_TO_GET_ACCOUNTS: 'ERROR_TO_GET_ACCOUNTS',
    ERROR_TO_CREATE_ORDER: 'ERROR_TO_CREATE_ORDER',
    SUCCESS_TO_CREATE_ORDER: 'SUCCESS_TO_CREATE_ORDER'
};

export { CREATE_ORDER_CONSTANTS };
